name: 'Run golangci-lint'
description: 'Run golangci-lint on push.'
author: 'wacul (forked from reviewdog)'
inputs:
  golangci_lint_flags:
    description: 'golangci-lint flags. (golangci-lint run --out-format=line-number <golangci_lint_flags>)'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.golangci_lint_flags }}
branding:
  icon: 'check-circle'
  color: 'blue'
